version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/my-web-app.war
    - appspec.yml
  discard-paths: yes
